# Generated by Django 6.0.3 on 2026-03-23 16:42

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('short_name', models.CharField(max_length=50, unique=True)),
                ('counterparty_type', models.CharField(choices=[('BANK', 'Bank'), ('CORP', 'Corporate'), ('GOVT', 'Government'), ('CB', 'Central Bank'), ('OTHER', 'Other')], default='BANK', max_length=10)),
                ('credit_rating', models.CharField(blank=True, default='', max_length=10)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum exposure limit in base currency', max_digits=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Counterparty',
                'verbose_name_plural': 'Counterparties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MoneyMarketDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_reference', models.CharField(editable=False, max_length=30, unique=True)),
                ('deal_type', models.CharField(choices=[('FD', 'Fixed Deposit'), ('CD', 'Call Deposit'), ('TB', 'Treasury Bill'), ('CP', 'Commercial Paper'), ('REPO', 'Repurchase Agreement'), ('RREPO', 'Reverse Repurchase Agreement'), ('COD', 'Certificate of Deposit')], max_length=10)),
                ('direction', models.CharField(choices=[('P', 'Placement'), ('B', 'Borrowing')], max_length=1)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('interest_rate', models.DecimalField(decimal_places=6, help_text='Annual interest rate as a decimal (e.g. 0.05 for 5%)', max_digits=8)),
                ('day_count_convention', models.CharField(choices=[('ACT/365', 'Actual/365'), ('ACT/360', 'Actual/360'), ('30/360', '30/360')], default='ACT/365', max_length=10)),
                ('trade_date', models.DateField()),
                ('settlement_date', models.DateField()),
                ('maturity_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('MATURED', 'Matured'), ('CANCELLED', 'Cancelled'), ('ROLLED', 'Rolled Over')], default='ACTIVE', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='money_market.counterparty')),
                ('rolled_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rolled_to_deals', to='money_market.moneymarketdeal')),
            ],
            options={
                'verbose_name': 'Money Market Deal',
                'verbose_name_plural': 'Money Market Deals',
                'ordering': ['-trade_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_date', models.DateField()),
                ('flow_type', models.CharField(choices=[('PRINC_IN', 'Principal Inflow'), ('PRINC_OUT', 'Principal Outflow'), ('INT_IN', 'Interest Inflow'), ('INT_OUT', 'Interest Outflow')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_settled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_flows', to='money_market.moneymarketdeal')),
            ],
            options={
                'verbose_name': 'Cash Flow',
                'verbose_name_plural': 'Cash Flows',
                'ordering': ['flow_date', 'deal'],
            },
        ),
    ]
